package com.eg0.network;

public enum MessageType {
	PLAYER_CREATE, PLAYER_JOIN, PLAYER_STARTGAME, PLAYER_SENDPICKS, PLAYER_SENDWINNER

	, SERVER_SENDROOMCODE, SERVER_SENDPLAYERS, SERVER_STARTGAME, SERVER_SENDCARDS, SERVER_SENDBLACK, SERVER_ASKPICKS, SERVER_SENDPICKS, SERVER_ASKWINNER, SERVER_SENDWINNER, SERVER_SENDENDGAME
}
